const freelancerCategories = [
  "Web Development",
  "Mobile App Development",
  "UI/UX Design",
  "Graphic Design",
  "Logo Design",
  "Video Editing",
  "Animation",
  "Content Writing",
  "Copywriting",
  "Technical Writing",
  "SEO",
  "Digital Marketing",
  "Social Media Management",
  "Email Marketing",
  "Sales & Business Development",
  "Customer Support",
  "Virtual Assistant",
  "Data Entry",
  "Data Analysis",
  "Machine Learning",
  "AI & Deep Learning",
  "DevOps",
  "Cloud Computing",
  "Cybersecurity",
  "Game Development",
  "Blockchain & Crypto",
  "Voice Over",
  "Translation",
  "Transcription",
  "Accounting & Bookkeeping",
  "Legal Consulting",
  "Business Consulting",
  "Market Research",
  "E-commerce Management",
  "Shopify Development",
  "WordPress Development",
  "Project Management",
  "Architecture & Interior Design",
  "3D Modeling & CAD",
  "Music Production",
  "Podcast Editing",
  "Financial Modeling",
  "Resume Writing",
  "Presentation Design",
  "Proofreading & Editing",
];

export default freelancerCategories;
