const skillsList = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C#",
  "C++",
  "Go",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "HTML",
  "CSS",
  "Sass",
  "Less",
  "React",
  "Vue.js",
  "Angular",
  "Next.js",
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "Spring Boot",
  "Laravel",
  "ASP.NET",
  "MongoDB",
  "MySQL",
  "PostgreSQL",
  "SQLite",
  "GraphQL",
  "REST API",
  "Redux",
  "MobX",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "Google Cloud",
  "Firebase",
  "Git",
  "CI/CD",
  "Jest",
  "Mocha",
  "Chai",
  "Cypress",
  "Selenium",
  "Webpack",
  "Babel",
  "Figma",
  "Adobe XD",
  "UI/UX Design",
  "Agile",
  "Scrum",
  "JIRA",
  "WordPress",
  "Shopify",
  "SEO",
  "Content Writing",
  "Copywriting",
  "Project Management",
  "Photoshop",
  "Illustrator",
  "Video Editing",
  "After Effects",
  "Premiere Pro",
  "3D Modeling",
  "Blender",
  "Unity",
  "Unreal Engine",
  "Mobile App Development",
  "React Native",
  "Flutter",
  "iOS Development",
  "Android Development",
  "Penetration Testing",
  "Cybersecurity",
  "Machine Learning",
  "Data Science",
  "Data Analysis",
  "Big Data",
  "Tableau",
  "Power BI",
  "SAP",
  "Salesforce",
  "Technical Writing",
  "Transcription",
  "Translation",
  "Virtual Assistant",
  "Customer Support",
  "Accounting",
  "Bookkeeping",
  "Business Analysis",
  "Marketing",
  "Social Media Management",
  "Email Marketing",
  "Google Ads",
  "Facebook Ads",
  "Affiliate Marketing",
];

export default skillsList;
